<a href="https://colab.research.google.com/github/rachanrv/Hackmaster/blob/master/States_Industry.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import shutil
import matplotlib.pyplot as plt
from matplotlib.pylab import rcParams
% matplotlib inline

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
   rcParams['figure.figsize'] = 20,10
   params = {'legend.fontsize': 'x-large',
            'axes.labelsize': 'x-large',
          'axes.titlesize':'x-large',
          'xtick.labelsize':'x-large',
          'ytick.labelsize':'x-large'}
   rcParams.update(params)

In [ ]:
df1=pd.read_csv('/content/drive/Shared drives/Build with AI/state_industry.csv')

In [ ]:
df1=df1.iloc[:,0:-6]
df1

      Unnamed: 0    State           Key_word  ...   Apr 2020   May 2020    Jun 2020
0              0  Alabama      Total nonfarm  ...     1865.8     1908.9   1954.2(P)
1              1  Alabama        labor force  ...  2198485.0  2239608.0  2195843(P)
2              2  Alabama         employment  ...  1895950.0  2023565.0  2030073(P)
3              3  Alabama       unemployment  ...   302535.0   216043.0   165770(P)
4              4  Alabama  unemployment rate  ...       13.8        9.6      7.5(P)
...          ...      ...                ...  ...        ...        ...         ...
1408        1408  Wyoming  Service-providing  ...      212.5      214.7    219.5(P)
1409        1409  Wyoming    Goods-producing  ...       49.9       49.1     48.7(P)
1410        1410  Wyoming      Total private  ...      195.6      199.1    202.5(P)
1411        1411  Wyoming   Nondurable Goods  ...        5.0        5.0      5.1(P)
1412        1412  Wyoming  unemployment rate  ...        9.6        8.8      7.6(P)

[1413 rows x 129 columns]

In [ ]:
for i in range(3,129,1):
  df1.iloc[:,i] = df1.iloc[:,i].astype(str)
  df1.iloc[:,i] = df1.iloc[:,i].str.replace('R', '')
  df1.iloc[:,i] = df1.iloc[:,i].str.replace('P', '')
  df1.iloc[:,i] = df1.iloc[:,i].str.replace('(', '').str.replace(')','')
  df1.iloc[:,i] = df1.iloc[:,i].astype(float)

df1=df1.iloc[:,[1,2,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128]]
#df1.to_csv('/content/drive/Shared drives/Build with AI/state_industryclean.csv')

In [ ]:
df1

        State           Key_word   Jan 2018  ...   Apr 2020   May 2020   Jun 2020
0     Alabama      Total nonfarm     2028.2  ...     1865.8     1908.9     1954.2
1     Alabama        labor force  2193503.0  ...  2198485.0  2239608.0  2195843.0
2     Alabama         employment  2108270.0  ...  1895950.0  2023565.0  2030073.0
3     Alabama       unemployment    85233.0  ...   302535.0   216043.0   165770.0
4     Alabama  unemployment rate        3.9  ...       13.8        9.6        7.5
...       ...                ...        ...  ...        ...        ...        ...
1408  Wyoming  Service-providing      235.0  ...      212.5      214.7      219.5
1409  Wyoming    Goods-producing       50.0  ...       49.9       49.1       48.7
1410  Wyoming      Total private      216.1  ...      195.6      199.1      202.5
1411  Wyoming   Nondurable Goods        5.2  ...        5.0        5.0        5.1
1412  Wyoming  unemployment rate        4.0  ...        9.6        8.8        7.6

[1413 rows x 32 columns]

In [ ]:
df1.reset_index()
df1.set_index(['State','Key_word'],inplace=True)

In [ ]:
index=df1.index
name=str(index[0][0])

In [ ]:
path='/content/drive/Shared drives/Build with AI/Final Plots'
try:
   os.mkdir(path)
except OSError:
  print ("Creation of the directory %s failed" % path)
else:
  print ("Successfully created the directory %s " % path)

Creation of the directory /content/drive/Shared drives/Build with AI/Final Plots failed

In [ ]:
for x in index:
  if x[0]==name:
    plt.plot(df1.loc[x,:],label=x[1])
    plt.title(name)
    plt.xticks(rotation=90)
    plt.xlabel('Month')
    plt.ylabel('Unemployment Rate')
  else:
    plt.legend(loc='center left', bbox_to_anchor=(1, 0.5),ncol=2, fancybox=True)
    plt.tight_layout()
    d1=os.path.join(path,name)
    plt.savefig(d1+'.png')
    plt.clf()
    name=x[0]

plt.legend(loc='center left', bbox_to_anchor=(1, 0.5),ncol=2, fancybox=True)
plt.tight_layout()    
d1=os.path.join(path,name)
plt.savefig(d1+'.png') 
plt.clf()

In [ ]:
df2=pd.read_csv('/content/drive/Shared drives/Build with AI/state_industryclean.csv')

In [ ]:
sectors=df2['Key_word']
sectors=sectors[sectors.duplicated(keep=False)]
sectors=sectors.drop_duplicates()

In [ ]:
sectors

0                            Total nonfarm
1                              labor force
2                               employment
3                             unemployment
4                        unemployment rate
5              employment-population ratio
6                               Government
7                           Other services
8                  Leisure and hospitality
9            Education and health services
10      Professional and business services
11                    Financial activities
12                             Information
13          Transportation and warehousing
14          labor force participation rate
15                         Wholesale trade
16                       Service-providing
17               Private service-providing
18                      Mining and logging
19                            Retail trade
20                         Goods-producing
21                           Total private
22    Trade, transportation, and utilities
23                        Nondurable Goods
24                           Manufacturing
25       Mining, Logging, and Construction
26                           Durable Goods
27                            Construction
Name: Key_word, dtype: object

In [ ]:
df2.reset_index()
df2.set_index(['Key_word','State'],inplace=True)
df2 = df2.apply(pd.to_numeric, errors='coerce')

In [ ]:
index=df2.index

In [ ]:
path='/content/drive/Shared drives/Build with AI/Final Plots on sector based'
try:
   os.mkdir(path)
except OSError:
  print ("Creation of the directory %s failed" % path)
else:
  print ("Successfully created the directory %s " % path)

Creation of the directory /content/drive/Shared drives/Build with AI/Final Plots on sector based failed

In [ ]:
for j in sectors:
  for x in index:
    if x[0]==j:
      plt.plot(df2.loc[x,:],label=x[1])
  plt.title(str(j))
  plt.xticks(rotation=90)
  plt.xlabel('Month')
  plt.ylabel('Unemployment Rate')
  plt.legend( loc='center left', bbox_to_anchor=(1, 0.5),ncol=3, fancybox=True)
  plt.tight_layout()
  name=str(j)
  d2=os.path.join(path,name)
  plt.savefig(d2+'.png')
  plt.clf()